FORMAT: 1A
HOST: https://my-road-conditions.herokuapp.com/

# Road Conditions

A simple API that allows programatic retrival of road condition data.

## Potholes Collection [/api/potholes]

### List All Potholes [GET]

+ Response 200 (application/json)

        [
            {
                "latitude": 37.100001,
                "longitude": -95.709999,
                "data": "2015-08-05T08:40:51.620Z"
            }
        ]