FORMAT: 1A
HOST: https://unbump.herokuapp.com/

# Road Conditions

A simple API that provides developers access to pothole location data.

## Potholes Collection [/api/potholes]

### List All Potholes [GET]

+ Response 200 (application/json)

        [
            {
                "latitude": 37.100001,
                "longitude": -95.709999,
                "date": "2015-08-05T08:40:51.620Z",
                "id": "f10f77850626f0017e6610d"
            }
        ]